###
# @name=Example2_Start
POST http://localhost:7289/api/example2
Content-Type: application/json

{
  "name": "MegaCorp"
}

> {%
    client.global.set("status_url", response.body.StatusQueryGetUri)
    client.global.set("instance_id", response.body.Id)
%}

###
# @name=Example2_Status
GET {{status_url}}

###
# @name=Example2_Infrastructure_Provisioned
POST http://localhost:7289/api/example2/{{instance_id}}/infrastructure

{
  "name": "MegaCorp"
}

###
# @name=Example2_Infrastructure_Provisioned
POST http://localhost:7289/api/example2/{{instance_id}}/application

{}