###
# @name=Example3_Start
POST http://localhost:7289/api/example3
Content-Type: application/json

{}

> {% client.global.set("status_url", response.body.StatusQueryGetUri) %}

###
# @name=Example3_Status
GET {{status_url}}

###
# @name=Example3_Stop
POST http://localhost:7289/api/example3/stop
Content-Type: application/json

{}