###
# @name example2_Start
POST http://localhost:7289/api/example2
Content-Type: application/json

{
  "name": "MegaCorp"
}

###
# @name example2_Status
GET {{example2_Start.response.body.StatusQueryGetUri}}

###
# @name example2_Infrastructure_Provisioned
POST http://localhost:7289/api/example2/{{example2_Start.response.body.Id}}/infrastructure

{
  "name": "MegaCorp"
}

###
# @name example2_Application_Deployed
POST http://localhost:7289/api/example2/{{example2_Start.response.body.Id}}/application

{}