###
# @name example3_Start
POST http://localhost:7289/api/example3
Content-Type: application/json

{}

###
# @name example3_Status
GET {{example3_Start.response.body.StatusQueryGetUri}}

###
# @name example3_Stop
POST http://localhost:7289/api/example3/stop
Content-Type: application/json

{}