###
# @name example1_Start
POST http://localhost:7289/api/example1
Content-Type: application/json

{
  "name": "MegaCorp"
}

###
# @name example1_Status
GET {{example1_Start.response.body.StatusQueryGetUri}}