namespace DurableDemo.Trial;

public class Crm
{
    public Task<CustomerInformation[]> GetExpiredTrials()
    {
        var random = Random.Shared;

        return Task.FromResult(CompanyNames
            .OrderBy(_ => random.Next())
            .Take(random.Next(5, 20))
            .Select(name => new CustomerInformation { Name = name })
            .ToArray());
    }

    private static readonly string[] CompanyNames =
    [
        "Quantum Crouton",
        "Glorp Dynamics",
        "Snazzlebee Solutions",
        "Elastic Turnip LLC",
        "Plasmatic Penguin",
        "NoodleForge Inc.",
        "WaffleTech Industries",
        "Pixel Platypus",
        "Grumbleberry Partners",
        "Squiggletronics",
        "Velvet Anvil Co.",
        "Bamboozle Bureau",
        "Nimbus Nomad",
        "Gravel & Glitter Corp.",
        "Blurp Innovations",
        "Zorp Logistics",
        "Puddle & Sprocket",
        "Lunar Loaf Enterprises",
        "Flibbertigibbet Ventures",
        "Jiggly Widget LLC",
        "Kaleidoscope Koala",
        "Turbo Wombat Inc.",
        "Button & Fluff Partners",
        "Infinite Nacho Systems",
        "Clamorous Codpieces Ltd.",
        "PogoPossum",
        "Chortleworks Co.",
        "Dandy Dingo Designs",
        "Platonic Pancake Corp.",
        "Orbiting Otter Solutions",
        "Funky Porridge LLC",
        "Gargantuan Jelly Ltd.",
        "Prickly Pear Syndicate",
        "Boomshackle Innovations",
        "Wonky Whale Enterprises",
        "Nimbus Fizz",
        "Fuzzy Spanner Works",
        "Toast Titan LLC",
        "Nebula Nougat Corp.",
        "Peppy Lizard Partners",
        "Squishworks Industries",
        "Quantum Yak LLC",
        "Burble & Snort Inc.",
        "Skylark Sausage Systems",
        "Jolly Pylon Ltd.",
        "Turbo Muffin Enterprises",
        "Knickknack Nexus",
        "Sproingy Solutions",
        "Luminous Llama Co.",
        "Whimsy Widgets LLC",
        "Mirthful Moose Mechanics",
        "Plucky Parrot Syndicate",
        "Frizzle & Fizz Innovations",
        "Noodle Nexus LLC",
        "Gusto Guppy Co.",
        "Chuckle Chinchilla Partners",
        "Sprightly Sparrow Systems",
        "Bumblebop Dynamics",
        "Wibble-Wobble Industries",
        "Jamboree Jelly Inc.",
        "Spaghetti Vortex LLC",
        "Toasty Tardigrades Ltd.",
        "Orbital Orangutan",
        "Happy Hedgehog Systems",
        "Snuggle Circuit Co.",
        "Perky Platypus Partners",
        "Cosmic Crayon Industries",
        "WhiffleWorks LLC",
        "Fluffy Nimbus Co.",
        "Turbo Trout Syndicate",
        "Bizarre Bazaar Partners",
        "Banana Anvil Systems",
        "Cheery Chimera Co.",
        "Bonkers Brigade Inc.",
        "Gravity Goose Enterprises",
        "Sassy Cactus Syndicate",
        "Nimbus Nebula Partners",
        "Shiny Marmot Mechanics",
        "Doodle Dingo Co.",
        "Flimsy Ferret Systems",
        "Glittery Gargoyle Inc.",
        "Perplexed Panda Partners",
        "Galactic Giraffe Co.",
        "Snappy Snail Enterprises",
        "Giggling Gnome Dynamics",
        "Radiant Raccoon Systems",
        "Wiggly Walrus Works",
        "Sprightly Squid LLC",
        "Puffin Popcorn Partners",
        "Jolly Jackalope Inc.",
        "Chipper Chameleon Systems",
        "Rocket Tortoise LLC",
        "Mirth Magnet Corp.",
        "Blazing Beaver Co.",
        "Fizz Fennec Enterprises",
        "Puffy Pterodactyl Syndicate",
        "Orbiting Oyster Solutions",
        "Wobble Weasel Works",
        "Snazzy Sardine Corp.",
        "Whacky Wombat Industries"
    ];
}